version: '3.1'

services:

  db:
    container_name: my_postgres
    ports:
        - '5050:5050'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: pg
      POSTGRES_DB: test
      
  adminer:
    image: adminer
    restart: always
    ports:
      - '8083:8080'
