version: '3.1'

services:
  mongo:
    container_name: my_mongo
    image: mongo
    restart: always
    ports:
        - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
  adminer:
    image: adminer
    restart: always
    ports:
      - '8083:8080'